/// <reference types="@capacitor/cli" />

/**
 * reCAPTCHA configuration available from `capacitor.config.ts`.
 *
 * Platform-specific keys win over `siteKey`.
 */
export interface RecaptchaPluginConfig {
  /**
   * Shared site key used when no platform-specific key is provided.
   *
   * For native apps, use a mobile application key from Google Cloud.
   * For Web, use a website key.
   *
   * @since 8.0.0
   */
  siteKey?: string;

  /**
   * Android site key. This value is preferred on Android.
   *
   * @since 8.0.0
   */
  androidSiteKey?: string;

  /**
   * iOS site key. This value is preferred on iOS.
   *
   * @since 8.0.0
   */
  iosSiteKey?: string;

  /**
   * Web site key. This value is preferred by the Web implementation.
   *
   * @since 8.0.0
   */
  webSiteKey?: string;

  /**
   * Use the Enterprise web script (`enterprise.js`) when running on Web.
   *
   * Android and iOS always use Google's mobile reCAPTCHA SDK.
   *
   * @default true
   * @since 8.0.0
   */
  enterprise?: boolean;

  /**
   * Optional language code for the Web reCAPTCHA script.
   *
   * @since 8.0.0
   * @example "en"
   */
  language?: string;
}

declare module '@capacitor/cli' {
  export interface PluginsConfig {
    /**
     * Configuration for `@capgo/capacitor-recaptcha`.
     *
     * @since 8.0.0
     */
    Recaptcha?: RecaptchaPluginConfig;
  }
}

/**
 * Options used to load the reCAPTCHA client.
 */
export interface LoadOptions {
  /**
   * Site key to use for this call.
   *
   * If omitted, the plugin reads the platform-specific key from Capacitor config.
   *
   * @since 8.0.0
   */
  siteKey?: string;

  /**
   * Android site key alias accepted for easier migration from older Cordova code.
   *
   * @since 8.0.0
   */
  androidSiteKey?: string;

  /**
   * iOS site key.
   *
   * @since 8.0.0
   */
  iosSiteKey?: string;

  /**
   * Web site key.
   *
   * @since 8.0.0
   */
  webSiteKey?: string;

  /**
   * Use the Enterprise web script (`enterprise.js`) when running on Web.
   *
   * @default true
   * @since 8.0.0
   */
  enterprise?: boolean;

  /**
   * Optional language code for the Web reCAPTCHA script.
   *
   * @since 8.0.0
   */
  language?: string;
}

/**
 * Result returned after the client is loaded.
 */
export interface LoadResult {
  /**
   * Whether the platform client is ready.
   *
   * @since 8.0.0
   */
  loaded: boolean;

  /**
   * Site key used to load the client.
   *
   * @since 8.0.0
   */
  siteKey: string;

  /**
   * Whether Enterprise mode was requested.
   *
   * @since 8.0.0
   */
  enterprise: boolean;

  /**
   * Platform that loaded the client.
   *
   * @since 8.0.0
   */
  platform: 'web' | 'ios' | 'android';
}

/**
 * Options used to execute a protected action.
 */
export interface ExecuteOptions extends LoadOptions {
  /**
   * Action name to protect.
   *
   * Use meaningful names such as `login`, `signup`, `checkout`, or `password_reset`.
   *
   * @since 8.0.0
   */
  action: string;

  /**
   * Optional native execution timeout in milliseconds.
   *
   * Android and iOS enforce a minimum timeout of 5000ms when provided.
   * This value is ignored on Web.
   *
   * @since 8.0.0
   */
  timeout?: number;
}

/**
 * Result returned after executing a protected action.
 */
export interface ExecuteResult {
  /**
   * Token generated by reCAPTCHA. Send this to your backend and create an assessment there.
   *
   * @since 8.0.0
   */
  token: string;

  /**
   * Action name used to generate the token.
   *
   * @since 8.0.0
   */
  action: string;

  /**
   * Site key used to generate the token.
   *
   * @since 8.0.0
   */
  siteKey: string;

  /**
   * Whether Enterprise mode was requested.
   *
   * @since 8.0.0
   */
  enterprise: boolean;

  /**
   * Platform that generated the token.
   *
   * @since 8.0.0
   */
  platform: 'web' | 'ios' | 'android';
}

/**
 * Plugin version payload.
 */
export interface PluginVersionResult {
  /**
   * Version identifier returned by the platform implementation.
   *
   * @since 8.0.0
   */
  version: string;
}

/**
 * reCAPTCHA plugin API.
 */
export interface RecaptchaPlugin {
  /**
   * Load and cache the reCAPTCHA client for the current platform.
   *
   * `execute()` loads the client automatically when needed, so calling this method is optional.
   *
   * @since 8.0.0
   */
  load(options?: LoadOptions): Promise<LoadResult>;

  /**
   * Execute reCAPTCHA for an action and return a token for backend assessment.
   *
   * @since 8.0.0
   */
  execute(options: ExecuteOptions): Promise<ExecuteResult>;

  /**
   * Returns the platform implementation version marker.
   *
   * @since 8.0.0
   */
  getPluginVersion(): Promise<PluginVersionResult>;
}
